version: '3'
volumes:
     fuseki-data:

services:

    db:
        environment:
            MYSQL_DATABASE: db
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: root
        image: mysql:latest
        ports:
          - 3307:3307
    web:
        build: .
        command: python3 questAPI/manage.py runserver 0.0.0.0:8000
        volumes:
            - $PWD/www:/var/www/html
        ports:
            - "8000:8000"
        depends_on:
            - db
    fusekidata:
        image: busybox
        volumes:
            - fuseki-data:/fuseki/databases
    fuseki:
        image: stain/jena-fuseki:3.4.0
        ports:
            - "3030:3030"
        volumes:
            - fuseki-data:/fuseki/databases
        environment:
            - ADMIN_PASSWORD=admin
            - FUSEKI_BASE=/fuseki
            - JVM_ARGS=-Xms2g -Xmx4g


